### ISSUE TITLE
語意分割的YOLO如何轉COCO

### ISSUE THREAD

**Issue by stphtan94117** [RapidAI/LabelConvert#6]
作者你好
由於yolov5跟yolov7都有出了語意分割(segmentation)，因此save_txt的內容，就不像傳統的只有bbox xywh值
而是有多個點組成的polygon

不曉得作者您能否做一個polygon的yolo(txt)轉COCO (json)方式
謝謝

**Comment by SWHL** [comment]
- 最近比较忙，这个有空时可能会做。
- 如果你这边写一下，可以提个PR，我很乐意给你合并进去的

**Comment by stphtan94117** [comment]
你好
這方面我也不是寫CODE高手，我只能提供相關yolo segmentation 檔案給你參考
讓你打開TXT檔，看它內容長怎樣
[](https://universe.roboflow.com/chonnam-national-university/crack-bphdr/dataset/1)

下載時候，麻煩選擇yolov5 or v7 pytorch，裡面就是txt了

**Comment by SWHL** [comment]
嗯嗯，你这个需求作为TODO，有空我看一下

**Comment by stphtan94117** [comment]
謝謝你
再麻煩妳新增yolo2coco、coco2yolo
或者正棒的是 json2yolo互轉

**Comment by bit-scientist** [comment]
Well, here we are. @SWHL did you happen to make it?

**Comment by SWHL** [comment]
I want to do this but don't have the time.
Your contributions are welcome, if you can.

**Comment by Youho99** [comment]
The YoloSeg2COCO functionality also interests me.
Any news on a possible implementation?

**Comment by SWHL** [comment]
在`label_convert >=0.0.10`中，已经支持了yolo seg格式转为coco格式。label_conert会自动处理seg类标注。具体可参见文档：[link](https://rapidai.github.io/LabelConvert/docs/supportconversions/yolov5_yaml_to_coco/)

In `label_convert >=0.0.10`, the conversion of yolo seg format to coco format is already supported. label_conert will automatically handle seg class annotations. For details, please refer to the document: [link](https://rapidai.github.io/LabelConvert/docs/supportconversions/yolov5_yaml_to_coco/)

**Comment by SWHL** [comment]
This issue will be closed. If you have any question, welcome to reopen it.
